jar_url: 'https://www.adobe.com/express/feature/image/convert/jpg-to-png/media_1b0ad89a4a5ad233f5708e21b5998d6638cb07929.png?width=2000&format=webply&optimize=medium'
zip_url: ''
folder_path: 'images_httpx'
file_name: '/image_chunks_f.png'
